FROM python:3.7.6
ENV PYTHONUNBUFFERED 1
#DEPENDENCIAS
RUN apt-get update
RUN apt-get -f install
#RUN apt-get install -y build-essential python3.6-dev  libmysqlclient-dev
ADD requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
# load project files and set work directory
ADD . /app/
WORKDIR /app
CMD  streamlit run app.py